SELECT YEAR(o.SALES_DATE) as YEAR, MONTH(o.SALES_DATE) as MONTH, u.GENDER as GENDER, COUNT(distinct o.USER_ID) as USERS
FROM ONLINE_SALE o
JOIN USER_INFO u
ON o.USER_ID = u.USER_ID
WHERE u.GENDER is NOT NULL
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), u.GENDER
ORDER BY 1, 2, 3