SELECT YEAR, MONTH, COUNT(*) PUCHASED_USERS, ROUND(COUNT(*) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) PUCHASED_RATIO
FROM
(SELECT DISTINCT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, U.USER_ID
FROM ONLINE_SALE S
JOIN USER_INFO U
ON S.USER_ID = U.USER_ID 
WHERE YEAR(JOINED) = 2021) A
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
