SELECT a.PRODUCT_CODE, a.PRICE*b.CNT SALES
FROM PRODUCT a
JOIN 
(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) CNT
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) b
WHERE a.PRODUCT_ID = b.PRODUCT_ID
ORDER BY 2 desc, 1 asc;