SELECT b.HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS a, 
(SELECT TO_CHAR(DATETIME, 'hh24') HOUR, ANIMAL_ID
FROM ANIMAL_OUTS) b
WHERE a.ANIMAL_ID = b.ANIMAL_ID AND 9 <= b.HOUR AND b.HOUR <= 19 
GROUP BY b.HOUR
ORDER BY b.HOUR;