SELECT A.CATEGORY, A.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F, 
(SELECT CATEGORY, MAX(PRICE) MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY in ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) A
WHERE F.CATEGORY = A.CATEGORY AND F.PRICE = A.MAX_PRICE
ORDER BY MAX_PRICE desc;